const fs = require('fs')
const bytecode_reg = /bytecode: */

// Logs is the path to the logs that will be analyzed
// Info is the data from the build/contracts folder
module.exports = (logs, info, callback) => {
  fs.readFile(logs, (error, contents) => {
    if (error) callback(error)
    let arr = contents.toString('utf8').split('\n')
    let tracker = {} 
    // Set arr to be all of the lines after line 362. The reason
    // why this is necessary is because pre-compile contracts are 
    // deployed every time ganache-cli is run. It is simply faster
    // to not analyze the logs generated by these transactions.
    arr = arr.slice(362, arr.length)
    for (let i = 0; i < arr.length; i += 2) {
      let bytecode = arr[i].slice(10, arr[i].length)
      let pc = Number(elem.slice(4, elem.length))
      if (tracker[bytecode]) {
        tracker[bytecode].test_pcs.add(pc)
      } else if (bytecode !== "") {
        let contract
        for (let j = 0; j < info.length; j++) {
          if (bytecode === info[j].bytecode) {
            info[j].test_pcs.add(pc)
            tracker[bytecode] = info[j]
            break
          }
        }
      } else {
        /* TODO: This is the constructor case */
      }
    }
  })
}
