const fs = require('fs')
const pc_reg = /pc:*/
const address_reg = /address:*/
const codehash_reg = /codehash:*/
const bytecode_reg = /bytecode:*/

// Logs is the path to the logs that will be analyzed
// Info is the data from the build/contracts folder
module.exports = (logs, info, callback) => {
  fs.readFile(logs, (error, contents) => {
    if (error) callback(error)
    let arr = contents.toString('utf8').split('\n')
    // Set arr to be all of the lines after line 982. The reason
    // why this is necessary is because pre-compile contracts are 
    // deployed every time ganache-cli is run. It is simply faster
    // to not analyze the logs generated by these transactions.
    arr = arr.slice(982, arr.length)
    // TODO - Analysis of the logs
  })
}
